stages:
  - build

before_script:
  - echo "$CI_REGISTRY_USER"
  - echo "$CI_REGISTRY_PASSWORD"
  - echo "$CI_REGISTRY"

docker-build:
  image: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  services:
    - name: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  stage: build
  script:
    - docker login -u "$ROBOT""$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t ruby-test-ac:latest .
    - docker tag ruby-test-ac:latest "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - docker push "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - sleep 10

