
51
variables:
   ROBOT: 'robot$'
   DOCKER_HOST: tcp://localhost:2375/
   DOCKER_TLS_CERTDIR: ""
before_script:
  - echo "$CI_REGISTRY_USER"
  - echo "$CI_REGISTRY_PASSWORD"
  - echo "$CI_REGISTRY"
stages:
  - build
  - test
docker-build:
  image: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  services:
    - name: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  stage: build
  script:
    - docker login -u "$ROBOT""$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t ruby-test-ac:latest .
    - docker tag ruby-test-ac:latest "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - docker push "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - sleep 10
  only:
    refs:
    - test-build
    - docker-build
docker-test:
  stage: test
  script:
    - export http_proxy=http://proxy-us.intel.com:911; export https_proxy=http://proxy-us.intel.com:912; export no_proxy=intel.com
    - apt-get update
    - apt-get install curl wget unzip -yq
    - ./download_intel_cert.sh
    - curl -L -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/latest.txt)/bin/linux/amd64/kubectl && chmod +x /usr/bin/kubectl && kubectl version --client
    - echo "$KUBE_URL"
    - echo "$KUBECONFIG"
    - cat "$KUBECONFIG"
    - kubectl apply -f k8s/ruby_dep.yaml
  tags:
    - medium-caas
  environment:
    name: testing
  only:
    refs:
    - test-build
    - kub-build