image: amr-registry-pre.caas.intel.com/pse-pswe-software-ba/gitlab:base

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  http_proxy: http://proxy-chain.intel.com:911
  https_proxy: http://proxy-chain.intel.com:911
  no_proxy: localhost,127.0.0.0/8,10.0.0.0/8,.intel.com,10.43.164.84,10.42.21.228
  ROBOT: 'robot$'
  
before_script:
  - echo "$CI_REGISTRY_USER"
  - echo "$CI_REGISTRY_PASSWORD"
  - echo "$CI_REGISTRY"


#### STAGES ######
stages:
  - build
#  - test

####  BUILD  ######
docker-build:
  stage: build
  tags: [my-runner]
  services:
    - name: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  script:
    - docker images
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY"/pse-pswe-software-ba/embeded:1.1 .
    - docker push "$CI_REGISTRY"/pse-pswe-software-ba/embeded:1.1
    - sleep 10
  environment:
    name: DEV environment

#    - cd base_image
#    - docker build -t "$CI_REGISTRY"/pse-pswe-software-ba/embeded:base .
#    - docker push "$CI_REGISTRY"/pse-pswe-software-ba/embeded:base
#    - sleep 10
#    - cd ..

#docker-test:
#  stage: test
#  script:
#    - export http_proxy=http://proxy-us.intel.com:911; export https_proxy=http://proxy-us.intel.com:912; export no_proxy=intel.com
#    - chmod 777 ./download_intel_cert.sh
#    - ./download_intel_cert.sh
#    - echo "$KUBE_URL"
#    - echo "$KUBECONFIG"
#    - cat "$KUBECONFIG"
#    - kubectl apply -f k8s/ruby_dep.yaml
#  tags:
#    - my-runner
#  environment:
#    name: testing


