image: amr-registry-pre.caas.intel.com/pse-pswe-software-ba/gitlab:base

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  http_proxy: http://proxy-chain.intel.com:911
  https_proxy: http://proxy-chain.intel.com:911
  no_proxy: localhost,127.0.0.0/8,10.0.0.0/8,.intel.com,10.43.164.84,10.42.21.228
  ROBOT: 'robot$'
  
before_script:
  - echo "$CI_REGISTRY_USER"
  - echo "$CI_REGISTRY_PASSWORD"
  - echo "$CI_REGISTRY"


#### STAGES ######
stages:
  - build

####  BUILD  ######
docker-build:
  stage: build
  tags: [my-runner]
  services:
    - name: amr-registry.caas.intel.com/caas/docker:19.03.1-dind
  script:
    - docker login -u "$ROBOT""$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t ruby-test-ac:latest .
    - docker tag ruby-test-ac:latest "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - docker push "$CI_REGISTRY"/actestrunners/ruby-test-ac:latest
    - sleep 10
  only:
    refs:
    - docker-build
  environment:
    name: DEV environment
  when: manual

