image: amr-registry-pre.caas.intel.com/pse-pswe-software-ba/gitlab:base

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  http_proxy: http://proxy-chain.intel.com:911
  https_proxy: http://proxy-chain.intel.com:911
  no_proxy: localhost,127.0.0.0/8,10.0.0.0/8,.intel.com,10.43.164.84,10.42.21.228


#### STAGES ######
stages:
  - build

####  BUILD  ######
build_proj:
  stage: build
  tags: [my-runner]
  services:
    - name: docker:dind
  script: 
  - docker build --build-arg HTTP_PROXY=http://proxy-chain.intel.com:911 --build-arg HTTPS_PROXY=http://proxy-chain.intel.com:911 -t pse-pswe-software-ba:dev .
  environment:
    name: DEV environment
  when: manual
