apiVersion: v1
kind: Service
metadata:
  name: ruby-test-service
  labels:
    app: ruby-test
spec:
  type: NodePort
  selector:
    app: ruby-test
  ports:
    - protocol: TCP
      port: 5000 
      nodePort: 31000
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ruby-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-test
  template:
    metadata:
      labels:
        app: ruby-test
    spec:
      containers:
        - name: ruby-test
          image: amr-registry-pre.caas.intel.com/actestrunners/ruby-test-ac:latest
          ports:
          - containerPort: 80
