#!/bin/bash

mkdir pem
cd pem

HOST="docker:dind"
openssl genrsa -aes256 -passout pass:docker -out ca-key.pem 4096
openssl rsa -in ca-key.pem -passin pass:docker -out ca-key.pem
openssl req -new -x509 -days 3650 -key ca-key.pem -sha256 -subj "/CN=docker:dind" -out ca.pem
openssl genrsa -out server-key.pem 4096
openssl req -subj "/CN=$HOST" -sha256 -new -key server-key.pem -out server.csr
echo subjectAltName = DNS:$HOST,IP:10.10.10.20,IP:127.0.0.1 >> openssl.cnf
echo extendedKeyUsage = serverAuth >> openssl.cnf
openssl x509 -req -days 3650 -sha256 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile openssl.cnf

openssl genrsa -out key.pem 4096
openssl req -subj '/CN=docker:dind client' -new -key key.pem -out client.csr
echo extendedKeyUsage = clientAuth > openssl-client.cnf
openssl x509 -req -days 3650 -sha256 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile openssl-client.cnf

rm -v client.csr server.csr openssl.cnf openssl-client.cnf
chmod -v 0400 ca-key.pem key.pem server-key.pem
chmod -v 0444 ca.pem server-cert.pem cert.pem
